spring.application.name=bookhub_api


#Connexion à la base de donnees
spring.datasource.url=jdbc:sqlserver://localhost;databasename=BOOK_HUB;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=kolixa


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create